project_id = "vbqzxtpljxgewaxjzmwf"

[functions.generate-script]
verify_jwt = true

[functions.edit-script]
verify_jwt = true

[functions.ai-video-captions]
verify_jwt = true

[functions.ai-silence-removal]
verify_jwt = true

[functions.multi-cam-session]
verify_jwt = true