// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbqzxtpljxgewaxjzmwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicXp4dHBsanhnZXdheGp6bXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNTczODYsImV4cCI6MjA3NTczMzM4Nn0.jF3V06HiH8arQH_Oq3J3AnFo_1ouHE9oG-Ap8ly_zrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});