// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzneapcybbqaivouwxyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bmVhcGN5YmJxYWl2b3V3eHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTk3NTEsImV4cCI6MjA3NDA5NTc1MX0.otkXMUeJFNglW_UnzzkaT5vTnp5atnECTJwISMSbXY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});